CREATE TABLE IF NOT EXISTS state_raw (
  SUMLEV INTEGER NOT NULL,
  REGION INTEGER NOT NULL,
  DIVISION INTEGER NOT NULL,
  STATE INTEGER NOT NULL,
  NAME TEXT NOT NULL,
  SEX INTEGER NOT NULL, -- Ignore this
  AGE INTEGER NOT NULL, -- Ignore this
  CENSUS2010POP INTEGER NOT NULL,
  ESTIMATESBASE2010 INTEGER NOT NULL,
  POPESTIMATE2010 INTEGER NOT NULL,
  POPESTIMATE2011 INTEGER NOT NULL,
  UNIQUE(STATE),
  UNIQUE(NAME)
);
.mode csv
.import state_raw.csv state_raw
